### ISSUE TITLE
non va 

### ISSUE THREAD

**Issue by rosarioV25** [AidanE122/PyTrader#1]
ho installato python 3.10.4 ho immesso tutte le mie key ma quando faccio per aprire il fail bach non va . ce si apre per 1o2 secondi ma poi si chiude e non va piu comunque nella mia key privata in fondo ho 2 segni di questo genere == me la prende lo stesso visto che devo mettere = in fondo ???? aiutami

**Comment by AidanE122** [comment]
Ciao, grazie per avermi contattato. Se possibile, prova ad aprire il file
.bat in un editor di testo e aggiungi "pause" alla riga sotto il programma
che è già stato scritto. Questo dovrebbe visualizzare il messaggio di
errore senza chiudersi immediatamente. Fammi sapere qual è il messaggio di
errore se sei in grado di farlo. Inoltre, non includere i segni di uguale
(==) durante la digitazione delle informazioni API nel documento. Quelli
sono stati inclusi solo per mostrare dove gli utenti dovrebbero inserire le
loro informazioni API.

**Comment by rosarioV25** [comment]
questo è quello che mi esce 

Traceback (most recent call last):
  File "C:\Users\rosario\Desktop\PyTrader-Update\main.py", line 3, in <module>
    from Console import *
  File "C:\Users\rosario\Desktop\PyTrader-Update\Console.py", line 1, in <module>
    import tradingview_ta
  File "C:\Users\rosario\AppData\Local\Programs\Python\Python310\lib\site-packages\tradingview_ta\__init__.py", line 1, in <module>
    from .main import TA_Handler, TradingView, Analysis, Interval, Exchange, get_multiple_analysis, __version__
  File "C:\Users\rosario\AppData\Local\Programs\Python\Python310\lib\site-packages\tradingview_ta\main.py", line 5, in <module>
    import requests, json, datetime, warnings
  File "C:\Users\rosario\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils
  File "C:\Users\rosario\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 29, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "C:\Users\rosario\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 174, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
Premere un tasto per continuare . . .

**Comment by AidanE122** [comment]
Mi scuso per il ritardo nella risposta, ho dovuto apportare alcune
modifiche al repository. Si prega di leggere il file "packages.txt" che ho
aggiunto al repository GitHub per informazioni su come correggere l'errore
"MutableMapping".
